
spring:
  application:
    name: order-service1
  cloud:
    nacos:
      server-addr: 192.168.235.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
server:
  port: 8020